
# OpenAPI спецификация генерируется автоматически с помощью springdoc-openapi.
# Все эндпоинты и модели данных описаны через аннотации @Operation.
# Swagger UI доступен по адресу: http://localhost:8080/swagger-ui/index.html#/
# Увидел этот файл только в конце. Раньше всегда генерировал описания с помощью springdoc-openapi